# Generated by Django 4.2.1 on 2023-05-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onemusic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
