# Generated by Django 4.2.1 on 2023-05-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onemusic', '0005_transaction_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
