# Generated by Django 4.2.1 on 2023-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemusic', '0007_delete_transaction_cart_date_cart_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
